
spring:
  batch:
    initialize-schema: ALWAYS
  datasource:
    initialization-mode: ALWAYS
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
  data:
    gemfire:
      pool:
        default:
          locators: localhost[10334]


sql: select * from ACCOUNT