DROP TABLE IF EXISTS SOURCE_ACCOUNT;

CREATE TABLE SOURCE_ACCOUNT  (
	test1 VARCHAR(100) NOT NULL,
	test2 VARCHAR(100) NOT NULL,
	test3 VARCHAR(100) NOT NULL
) ;

DROP TABLE IF EXISTS ACCOUNT_ENTITY;

CREATE table ACCOUNT_ENTITY (
 ACCOUNT_ID varchar(100) NOT NULL,
 name  varchar(100) NOT NULL
);

DROP TABLE IF EXISTS DEST_ACCOUNT;

CREATE TABLE DEST_ACCOUNT  (
	test1 VARCHAR(100) NOT NULL,
	test2 VARCHAR(100) NOT NULL,
	test3 VARCHAR(100) NOT NULL
) ;