spring:
  flyway:
    enabled: false
    baselineOnMigrate: false
  batch:
    chunkSize: 10
    throttleLimit: 1
    initialize-schema: never
  datasource:
    initialization-mode: ALWAYS
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: none



sql: select * from ACCOUNT